//What is the output of:
if ('') 
    { console.log('yes'); 

    } 
    else {
         console.log('no'); 
        }
//Output: no

//empty string is falsy value in JavaScript, 
// so the condition in the if statement evaluates to false, 
// and the else block is executed, resulting in the output "no".

//Q:Which value is NOT falsy in JavaScript? 0 or ' ' or '0' or null ?
//Ans: Output: '0'
//In JavaScript, the following values are considered falsy:
// - false
// - 0 (zero)
// - '' (empty string)
// - null
// - undefined
// - NaN (Not a Number)
